#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# See Allwmake/etc/sourceme.sh - keeps WM_PROJECT_USER_DIR/FOAM_USER_*BIN
# pointed at this repository regardless of where it lives or what the local
# username is.
. ./etc/sourceme.sh

wclean applications/utilities/setLogNormal
wclean applications/solvers/thermoParcelFoam
wclean applications/solvers/bubbleFoam
wclean applications/solvers/msfrParcelFoam
wclean applications/solvers/nuclearParcelFoam

wclean src/nuclearCloudFvOptions
wclean src/kinematicCloudFvOptions
wclean src/nuclear
wclean src/flotation
wclean src/LogMoM
wclean src/myTurbulence
wclean src/myIntermediate

rm -rf platforms

#------------------------------------------------------------------------------
