#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# See Allwmake - keeps WM_PROJECT_USER_DIR (and FOAM_USER_*BIN) pointed at
# this repository regardless of where it lives or what the local username is.
export WM_PROJECT_USER_DIR="$PWD"
export FOAM_USER_APPBIN="$WM_PROJECT_USER_DIR/platforms/$WM_OPTIONS/bin"
export FOAM_USER_LIBBIN="$WM_PROJECT_USER_DIR/platforms/$WM_OPTIONS/lib"

wclean applications/utilities/setLogNormal
wclean applications/solvers/thermoParcelFoam
wclean applications/solvers/bubbleFoam
wclean applications/solvers/msfrParcelFoam
wclean applications/solvers/nuclearParcelFoam

wclean src/nuclearCloudFvOptions
wclean src/kinematicCloudFvOptions
wclean src/nuclear
wclean src/flotation
wclean src/LogMoM
wclean src/myTurbulence
wclean src/myIntermediate

rm -rf platforms

#------------------------------------------------------------------------------
