"""
caseDefaults.py - default settings for the bubbly-tube Euler-Euler case (OpenFOAM v2606).

You normally do NOT edit this file: run
    python3 setupCase.py
and answer the questions.  The values below are the suggested answers (press Enter to accept)
and the fixed settings that the questionnaire does not ask for (e.g. the liquid height).

Defaults follow F.L. de Wit, "Numerical and Experimental Assessment of Low-Reynolds
Two-Phase Bubble Loop Dynamics for Molten Salt Reactor Applications", MSc thesis,
TU Delft, 2025 (referred to below as [dW]).  Differences from [dW]: no baffle,
centred injector, OpenFOAM v2606 (ESI) instead of OpenFOAM-8 (Foundation).
"""

# =============================================================================
# Case
# =============================================================================
CASE_NAME = "tube_Q{Q}_d{db}_{turb}_{mesh}"   # placeholders: {Q} {db} {turb} {mesh}
OUTPUT_DIR = "cases"                          # relative to this file

# =============================================================================
# Geometry  [m]
# =============================================================================
TUBE_DIAMETER = 0.030        # [dW] Table 3.1
TUBE_HEIGHT = 0.35           # your column; [dW] rig 0.45 m, [dW] CFD 0.30 m (full) / 0.50 m (free surface)
LIQUID_HEIGHT = 0.30         # static liquid level, [dW] Table 3.1 - FIXED, not asked

# =============================================================================
# Mesh: curved O-grid (square core with arc edges + 4 outer blocks)
# =============================================================================
# Levels reproduce the cell sizes of the [dW] mesh study (Table C.1):
#   level       Nc  Nr   dz [mm]   [dW] cells (0.30 m)   h [mm]
#   coarse       8   4   3.0          19 200              2.2
#   medium      12   4   2.0          50 400              1.6
#   fine        16   6   1.5         128 000              1.2   <- [dW] blockMeshDict (App. C.3)
#   extrafine   22   8   1.154       308 880              0.9
# Nc = cells along each core edge / each 90 deg arc, Nr = radial cells in the outer ring.
MESH_LEVEL = "medium"
MESH_CUSTOM = None           # e.g. dict(Nc=14, Nr=5, dz=0.0018) overrides MESH_LEVEL

CORE_HALF_SIDE = 0.0075      # half-side of the core square [m]      ([dW]: 7.5 mm)
CORE_ARC_RADIUS = 0.0085     # radius of the core-edge arc midpoints [m] ([dW]: 8.5 mm)
                             # = CORE_HALF_SIDE -> straight core edges (classic O-grid)
RADIAL_GRADING = 1.0         # outer-ring grading, last/first cell (<1 refines at the wall); [dW]: 1

# =============================================================================
# Fluids (T = 293.15 K)
# =============================================================================
LIQUID = "AG40"              # "AG40" = 40 wt% aqueous glycerol [dW] Table 3.2, or "water"
TEMPERATURE = 293.15         # [K]  ([dW] ran at 300 K by mistake, footnote Table 8.6)

# =============================================================================
# Gas injection
# =============================================================================
Q_LPM = 0.3                  # gas flowrate [L/min]; a list, e.g. [0.1, 0.2, 0.3, 0.4, 0.5],
                             # creates one case per flowrate ([dW]: 0.1-0.5 L/min)
FLOW_REFERENCE = "actual"    # "actual" (20 C, 1 atm, as used in [dW]),
                             # "normal" (0 C, 1 atm - Bronkhorst ln/min), "standard" (20 C, 1 atm)
INJECTOR_DIAMETER = 1.0e-3   # orifice diameter [m] ([dW]: 1 mm gap in a flat plate)
INJECTOR_POSITION = (0.0, 0.0)   # (x, y) [m]; (0, 0) = centred.  [dW]: off-centre (riser)
INJECTOR_ZONE_RADIUS = None  # radius of the mass-source cellZone [m]; None = auto (>= 1.5 core cells)
INJECTOR_ZONE_HEIGHT = None  # height of the cellZone above the bottom [m]; None = auto (2 cells)
INJECTION_START = 0.01       # [s]  [dW]
INJECTION_DURATION = 1000.0  # [s]  [dW] used 40 s = whole run; keep > END_TIME for continuous injection

# =============================================================================
# Bubbles
# =============================================================================
# "auto": interpolate BUBBLE_TABLE at Q_LPM.  Or give a number [m].
BUBBLE_DIAMETER = "auto"
# [dW] Sec. 5.2: volume-equivalent riser bubble size 5 mm (0.1 L/min) -> 8.5 mm (0.5 L/min).
# Only the end points are stated in the text; the intermediate values are a LINEAR
# interpolation - replace them with values read off [dW] Fig. 5.2 or your own imaging.
# ([dW] CFD sensitivity study used a constant 3 mm, representative of DOWNCOMER bubbles,
#  d32 = 2.3-2.6 mm, Fig. 5.3 - not relevant without a baffle, see README.)
BUBBLE_TABLE = {0.1: 5.0e-3, 0.2: 5.875e-3, 0.3: 6.75e-3, 0.4: 7.625e-3, 0.5: 8.5e-3}
DIAMETER_MODEL = "isothermal"    # "isothermal" ([dW]) or "constant"
ASPECT_RATIO = "constant"        # "constant" (E = 1, [dW]), "Wellek", "VakhrushevEfremov", "Tomiyama"

# =============================================================================
# Physics
# =============================================================================
# "laminar"         : both phases laminar.  NOTE: all v2606 turbulent-dispersion models scale with
#                     the liquid k or nut, so turbulent dispersion is effectively OFF when laminar.
# "LaheyKEpsilon"   : liquid LaheyKEpsilon + gas continuousGasKEpsilon   ([dW] setups A, B)
# "kOmegaSSTSato"   : liquid kOmegaSSTSato + gas laminar                 ([dW] setup C)
# "mixtureKEpsilon" : mixtureKEpsilon in both phases (v2606 bubbleColumn tutorial)
TURBULENCE = "LaheyKEpsilon"

DRAG = "IshiiZuber"              # [dW]; alt: "TomiyamaCorrelated", "TomiyamaAnalytic", "SchillerNaumann"
LIFT = "Tomiyama"                # [dW]; alt: "constant" (uses LIFT_CL), None (no lift)
LIFT_CL = 0.288                  # used only if LIFT = "constant"
LIFT_WALL_DAMPING_CD = 1.0       # cosine damping over Cd*d_b from the wall ([dW] Eq. 8.13 with d_range = d_b);
                                 # None = no damping.  ([dW] 'zeroWallDist' has no v2606 equivalent)
WALL_LUBRICATION = None          # [dW]: none. alt: "Antal", "Frank", "Tomiyama"
# Turbulent dispersion: "LopezDeBertodano" ([dW] B: Ctd 2.0), "Burns" ([dW] C: Ctd 1.0, sigma 0.7), None
TURB_DISPERSION = "LopezDeBertodano"
TD_CTD = 2.0
TD_SIGMA = 0.7                   # Burns only
BURNS_START_TIME = 0.2           # Burns diverges from a still column in v2606: run LopezDeBertodano
                                 # until this time, then switch (done by Allrun)
VIRTUAL_MASS_CVM = 0.5           # [dW]

# =============================================================================
# Numerics and run control
# =============================================================================
END_TIME = 40.0                  # [s]  [dW]: 40 s
AVERAGE_START = 10.0             # [s]  start of fieldAverage and of the time-averaged statistics
WRITE_INTERVAL = 1.0             # [s]
FIXED_TIME_STEP = None           # e.g. 1e-3 = [dW] fixed dt; None = adaptive (MAX_CO)
MAX_CO = 0.5
MAX_DELTA_T = 1.0e-3
N_OUTER_CORRECTORS = 3           # [dW]
N_CORRECTORS = 1                 # [dW]
FACE_MOMENTUM = True             # stabilises the free surface (v2606 option)
RELAXATION = 1.0                 # [dW]: 0.85
N_PROCS = 8                      # [dW]: 16 on DelftBlue

# =============================================================================
# Measurements / sampling
# =============================================================================
# Heights of the LDA planes [m].  [dW]: main plane z = 0.15 m; vertical points at 0.05-0.25 m (App. C.4.6).
# Every height gets: LDA-point probes, 2 diameter lines, a sampled plane, and time series of the
# area-averaged void fraction and of the up/down liquid flow through the plane.
LDA_HEIGHTS = [0.05, 0.10, 0.15, 0.20, 0.25]
# LDA radial positions [m] ([dW] Fig. 6.2: 10 points per radial path, refined at centre and wall)
LDA_RADII = [0.0005, 0.0015, 0.0025, 0.0045, 0.0065, 0.0085, 0.0105, 0.0125, 0.0135, 0.0145]
# Angles of the radial paths [deg].  No baffle -> full circle; [dW] used 7 paths over a half circle.
LDA_ANGLES = [0, 45, 90, 135, 180, 225, 270, 315]
PROBE_WRITE_EVERY = 1            # write probes every N time steps (LDA statistics need every step)

WRITE_PHASE_FORCES = False       # write drag / lift / TD / VM force fields (diagnostics)
