#!/usr/bin/env python3
"""
setupCase.py - write an OpenFOAM v2606 reactingTwoPhaseEulerFoam case for a bubbly flow in a
vertical tube (curved O-grid, free surface, centred gas injector).

    python3 setupCase.py                     ask the questions (Enter = suggested answer)
    python3 setupCase.py --defaults          no questions, use caseDefaults.py
    python3 setupCase.py --from <file.py>    no questions, replay the caseSettings.py of an earlier case
    add --force to overwrite existing case directories without asking

One case is written per gas flowrate.  Run a case with ./Allrun inside it.
"""
import importlib.util
import math
import os
import re
import shutil
import sys
import types

HERE = os.path.dirname(os.path.abspath(__file__))

# ============================================================================= constants
G = 9.81
P_ATM = 101325.0
R_UNIVERSAL = 8314.46
T_STD_OF = 298.15            # OpenFOAM Tstd for hConst / eConst sensible energy

FLUIDS = {
    # [dW] Table 3.2 (AG40 at 293 K) and standard water data at 293 K
    "AG40":  dict(rho=1100.0, mu=3.63e-3, sigma=0.070, Cp=3350.0, W=26.6, Pr=25.33),
    "water": dict(rho=998.2, mu=1.002e-3, sigma=0.0728, Cp=4182.0, W=18.02, Pr=7.0),
}
AIR = dict(W=28.9, Cp=1007.0, mu=1.84e-5, Pr=0.7)          # [dW] Table 3.2

MESH_LEVELS = {                                          # [dW] Table C.1 cell sizes
    "coarse":    dict(Nc=8,  Nr=4, dz=0.003),
    "medium":    dict(Nc=12, Nr=4, dz=0.002),
    "fine":      dict(Nc=16, Nr=6, dz=0.0015),
    "extrafine": dict(Nc=22, Nr=8, dz=0.3 / 260),
}
TURB_TAGS = {"laminar": "lam", "LaheyKEpsilon": "kEps", "kOmegaSSTSato": "SST", "mixtureKEpsilon": "mixKEps"}

HDR = """/*--------------------------------*- C++ -*----------------------------------*\\
| OpenFOAM v2606 | bubbly tube | generated by setupCase.py (see caseSettings.py)  |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""
FTR = "\n// ************************************************************************* //\n"


# ============================================================================= helpers
def load_config(path):
    """Load a settings file into a plain namespace of its UPPER_CASE names."""
    spec = importlib.util.spec_from_file_location("settings", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return types.SimpleNamespace(**{k: getattr(mod, k) for k in dir(mod) if k.isupper()})


def save_config(cfg, path, note):
    with open(path, "w") as f:
        f.write(f'"""Settings used to generate this case ({note}).\n'
                f'Regenerate with:  python3 setupCase.py --from {os.path.basename(path)}"""\n\n')
        for k in sorted(vars(cfg)):
            f.write(f"{k} = {getattr(cfg, k)!r}\n")


def fmt(x):
    return f"{x:.6g}"


def indent(text, n):
    pad = " " * n
    return "\n".join(pad + l if l.strip() else l for l in text.strip("\n").splitlines())


class Case:
    def __init__(self, root):
        self.root = root

    def write(self, rel, body, cls="dictionary"):
        path = os.path.join(self.root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(HDR.format(cls=cls, obj=os.path.basename(rel)))
            f.write(body.strip("\n") + "\n" + FTR)

    def write_raw(self, rel, text, executable=False):
        path = os.path.join(self.root, rel)
        with open(path, "w") as f:
            f.write(text)
        if executable:
            os.chmod(path, 0o755)


def bubble_diameter(cfg, Q):
    if cfg.BUBBLE_DIAMETER != "auto":
        return float(cfg.BUBBLE_DIAMETER), "fixed in config"
    tab = sorted(cfg.BUBBLE_TABLE.items())
    qs, ds = [t[0] for t in tab], [t[1] for t in tab]
    if Q <= qs[0]:
        return ds[0], f"BUBBLE_TABLE (clipped to Q = {qs[0]})"
    if Q >= qs[-1]:
        return ds[-1], f"BUBBLE_TABLE (clipped to Q = {qs[-1]})"
    for (q0, d0), (q1, d1) in zip(tab, tab[1:]):
        if q0 <= Q <= q1:
            return d0 + (d1 - d0) * (Q - q0) / (q1 - q0), "BUBBLE_TABLE (interpolated)"


def tomiyama_cl(Eo, Re):
    f = 0.0010422 * Eo ** 3 - 0.0159 * Eo ** 2 - 0.0204 * Eo + 0.474    # v2606 coefficients
    if Eo < 4:
        return min(0.288 * math.tanh(0.121 * Re), f)
    if Eo <= 10.7:
        return f
    return -0.288


# ============================================================================= derived data
def derive(cfg, Q):
    d = {}
    liq = FLUIDS[cfg.LIQUID]
    d["liq"] = liq
    d["Q_lpm"] = Q
    R = cfg.TUBE_DIAMETER / 2
    d["R"] = R
    d["A"] = math.pi * R * R
    T = cfg.TEMPERATURE
    Rg = R_UNIVERSAL / AIR["W"]
    d["Rg"] = Rg
    T_ref = {"actual": T, "normal": 273.15, "standard": 293.15}[cfg.FLOW_REFERENCE]
    rho_ref = P_ATM / (Rg * T_ref)
    Qm3 = Q / 1000.0 / 60.0
    d["mdot"] = rho_ref * Qm3
    p_inj = P_ATM + liq["rho"] * G * cfg.LIQUID_HEIGHT
    rho_inj = p_inj / (Rg * T)
    d["p_inj"] = p_inj
    d["Q_actual_inj"] = d["mdot"] / rho_inj
    d["jg"] = d["mdot"] / (P_ATM / (Rg * T)) / d["A"]
    d["e_in"] = AIR["Cp"] * (T - T_STD_OF) - Rg * T      # hConst + perfectGas sensible e
    db, src = bubble_diameter(cfg, Q)
    d["db"], d["db_src"] = db, src

    # mesh
    m = dict(cfg.MESH_CUSTOM) if cfg.MESH_CUSTOM else dict(MESH_LEVELS[cfg.MESH_LEVEL])
    m["Nz"] = max(1, round(cfg.TUBE_HEIGHT / m["dz"]))
    m["dz"] = cfg.TUBE_HEIGHT / m["Nz"]
    m["cells"] = (m["Nc"] ** 2 + 4 * m["Nc"] * m["Nr"]) * m["Nz"]
    s, ra = cfg.CORE_HALF_SIDE, cfg.CORE_ARC_RADIUS
    m["d_core"] = 2 * s / m["Nc"]
    m["d_arc"] = 0.5 * math.pi * R / m["Nc"]
    m["d_rad_mean"] = (R - ra) / m["Nr"]
    g = cfg.RADIAL_GRADING
    if abs(g - 1) < 1e-9:
        m["d_rad_wall"] = (R - s * math.sqrt(2) + R - ra) / 2 / m["Nr"]
    else:  # geometric series, g = last/first
        L = R - ra
        rr = g ** (1 / (m["Nr"] - 1)) if m["Nr"] > 1 else 1
        first = L * (1 - rr) / (1 - rr ** m["Nr"]) if abs(rr - 1) > 1e-12 else L / m["Nr"]
        m["d_rad_wall"] = first * rr ** (m["Nr"] - 1)
    m["h"] = (d["A"] * cfg.TUBE_HEIGHT / m["cells"]) ** (1 / 3)
    d["mesh"] = m

    # injector zone
    zr = cfg.INJECTOR_ZONE_RADIUS or max(cfg.INJECTOR_DIAMETER / 2, 1.5 * m["d_core"])
    zh = cfg.INJECTOR_ZONE_HEIGHT or 2.0 * m["dz"]
    d["inj_r"], d["inj_h"] = zr, zh
    d["inj_cells_est"] = math.pi * zr * zr / (m["d_core"] ** 2) * (zh / m["dz"])

    # bubble numbers
    drho = liq["rho"] - P_ATM / (Rg * T)
    d["Eo"] = drho * G * db * db / liq["sigma"]
    d["Mo"] = G * liq["mu"] ** 4 * drho / (liq["rho"] ** 2 * liq["sigma"] ** 3)
    UT = 0.4          # [dW] measured rise velocity, Fig. 5.4
    d["Re_b"] = liq["rho"] * UT * db / liq["mu"]
    d["CL"] = tomiyama_cl(d["Eo"], d["Re_b"])
    # Tomiyama sign change: f(Eo) = 0
    lo, hi = 1.0, 10.0
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        if 0.0010422 * mid ** 3 - 0.0159 * mid ** 2 - 0.0204 * mid + 0.474 > 0:
            lo = mid
        else:
            hi = mid
    d["d_CL0"] = math.sqrt(lo * liq["sigma"] / (drho * G))
    return d


def checks(cfg, d):
    w = []
    m = d["mesh"]
    R = d["R"]
    if not (cfg.CORE_HALF_SIDE <= cfg.CORE_ARC_RADIUS < R * 0.8):
        w.append("CORE_ARC_RADIUS must be >= CORE_HALF_SIDE and well inside the tube radius.")
    if cfg.CORE_HALF_SIDE * math.sqrt(2) >= R * 0.85:
        w.append("CORE_HALF_SIDE too large: core corners come too close to the wall.")
    if cfg.LIQUID_HEIGHT >= cfg.TUBE_HEIGHT - 0.02:
        w.append("Less than 20 mm of head space: the swelling level may reach the outlet.")
    for z in cfg.LDA_HEIGHTS:
        if z <= d["inj_h"] + 0.01 or z >= cfg.LIQUID_HEIGHT - 0.01:
            w.append(f"LDA height z = {z} m is inside the injector zone or within 10 mm of the free surface.")
    for r in cfg.LDA_RADII:
        if r >= R:
            w.append(f"LDA radius {r} m is outside the tube.")
    if d["inj_cells_est"] < 4:
        w.append(f"Injector cellZone holds only ~{d['inj_cells_est']:.0f} cells: increase INJECTOR_ZONE_RADIUS/HEIGHT.")
    ratio = min(m["d_core"], m["d_rad_wall"], m["dz"]) / d["db"]
    if ratio < 0.25:
        w.append(f"Smallest cell / d_b = {ratio:.2f} < 0.25: far below the bubble size (see README, mesh section).")
    if cfg.LIFT_WALL_DAMPING_CD and cfg.LIFT_WALL_DAMPING_CD * d["db"] > 0.5 * R:
        w.append(f"Lift is damped over Cd*d_b = {1e3*cfg.LIFT_WALL_DAMPING_CD*d['db']:.1f} mm, i.e. over more than half the radius.")
    if cfg.TURBULENCE == "laminar" and cfg.TURB_DISPERSION:
        w.append("TURBULENCE = laminar: turbulent dispersion scales with k/nut and is therefore zero.")
    if cfg.TURB_DISPERSION == "Burns" and cfg.BURNS_START_TIME >= cfg.END_TIME:
        w.append("BURNS_START_TIME >= END_TIME: Burns will never be switched on.")
    if cfg.AVERAGE_START >= cfg.END_TIME:
        w.append("AVERAGE_START >= END_TIME: no time averaging.")
    if abs(d["db"] - d["d_CL0"]) < 0.5e-3:
        w.append(f"d_b = {1e3*d['db']:.2f} mm is within 0.5 mm of the Tomiyama lift sign change "
                 f"({1e3*d['d_CL0']:.2f} mm): results will be very sensitive to d_b.")
    return w


# ============================================================================= writers
def write_mesh(c, cfg, d):
    m = d["mesh"]
    R, H, s, ra = d["R"], cfg.TUBE_HEIGHT, cfg.CORE_HALF_SIDE, cfg.CORE_ARC_RADIUS
    g = cfg.RADIAL_GRADING
    # outer blocks run from the wall (vertices 4-7) to the core (0-3) in the local y
    # direction, so a grading of 1/g gives last/first = g from wall to core.
    gr = 1.0 / g
    c.write("system/blockMeshDict", f"""
// Curved O-grid ([dW] App. C.3): square core with arc edges + 4 outer blocks.
// z = axial (up), origin at the centre of the tube bottom.
scale   1;

R   {fmt(R)};     // tube radius
s   {fmt(s)};     // core half-side
ra  {fmt(ra)};    // radius of the core-edge arc midpoints (= s -> straight edges)
H   {fmt(H)};     // tube height

Rc  #eval{{ $R*sqrt(0.5) }};
sm  #eval{{ -$s }};
Rcm #eval{{ -$Rc }};
Rm  #eval{{ -$R }};
ram #eval{{ -$ra }};

vertices
(
    ($sm  $sm  0) ($s  $sm  0) ($s  $s  0) ($sm  $s  0)      // 0-3  core
    ($Rcm $Rcm 0) ($Rc $Rcm 0) ($Rc $Rc 0) ($Rcm $Rc 0)      // 4-7  wall
    ($sm  $sm $H) ($s  $sm $H) ($s  $s $H) ($sm  $s $H)      // 8-11
    ($Rcm $Rcm $H) ($Rc $Rcm $H) ($Rc $Rc $H) ($Rcm $Rc $H)  // 12-15
);

Nc  {m['Nc']};    // cells along each core edge / 90 deg arc
Nr  {m['Nr']};    // radial cells, outer ring
Nz  {m['Nz']};    // axial cells (dz = {1e3*m['dz']:.3f} mm)

blocks
(
    hex (0 1 2 3 8 9 10 11)     ($Nc $Nc $Nz) simpleGrading (1 1 1)        // core
    hex (4 5 1 0 12 13 9 8)     ($Nc $Nr $Nz) simpleGrading (1 {fmt(gr)} 1)  // -y
    hex (5 6 2 1 13 14 10 9)    ($Nc $Nr $Nz) simpleGrading (1 {fmt(gr)} 1)  // +x
    hex (6 7 3 2 14 15 11 10)   ($Nc $Nr $Nz) simpleGrading (1 {fmt(gr)} 1)  // +y
    hex (7 4 0 3 15 12 8 11)    ($Nc $Nr $Nz) simpleGrading (1 {fmt(gr)} 1)  // -x
);

edges
(
    arc 4 5 (0 $Rm 0)     arc 5 6 ($R 0 0)     arc 6 7 (0 $R 0)     arc 7 4 ($Rm 0 0)
    arc 12 13 (0 $Rm $H)  arc 13 14 ($R 0 $H)  arc 14 15 (0 $R $H)  arc 15 12 ($Rm 0 $H)
    arc 0 1 (0 $ram 0)    arc 1 2 ($ra 0 0)    arc 2 3 (0 $ra 0)    arc 3 0 ($ram 0 0)
    arc 8 9 (0 $ram $H)   arc 9 10 ($ra 0 $H)  arc 10 11 (0 $ra $H) arc 11 8 ($ram 0 $H)
);

boundary
(
    bottom
    {{
        type wall;
        faces ( (0 3 2 1) (4 0 1 5) (5 1 2 6) (6 2 3 7) (7 3 0 4) );
    }}
    wall
    {{
        type wall;
        faces ( (4 5 13 12) (5 6 14 13) (6 7 15 14) (7 4 12 15) );
    }}
    atmosphere
    {{
        type patch;
        faces ( (8 9 10 11) (12 8 9 13) (13 9 10 14) (14 10 11 15) (15 11 8 12) );
    }}
);
""")
    x0, y0 = cfg.INJECTOR_POSITION
    zl = min(cfg.LIQUID_HEIGHT - 0.005, cfg.LIQUID_HEIGHT)
    c.write("system/topoSetDict", f"""
actions
(
    {{   // gas mass source: {1e3*cfg.INJECTOR_DIAMETER:.2f} mm orifice at ({x0}, {y0}),
        // represented by a small cylinder of cells above it
        name    injectorCells;
        type    cellSet;
        action  new;
        source  cylinderToCell;
        point1  ({fmt(x0)} {fmt(y0)} 0);
        point2  ({fmt(x0)} {fmt(y0)} {fmt(d['inj_h'])});
        radius  {fmt(d['inj_r'])};
    }}
    {{
        name    injector;
        type    cellZoneSet;
        action  new;
        source  setToCellZone;
        set     injectorCells;
    }}
    {{   // liquid region below the initial free surface, above the injector (holdup monitor)
        name    liquidRegion;
        type    cellZoneSet;
        action  new;
        source  boxToCell;
        box     (-1 -1 {fmt(d['inj_h'])}) (1 1 {fmt(zl)});
    }}
);
""")
    c.write("system/setFieldsDict", f"""
defaultFieldValues
(
    volScalarFieldValue alpha.air   1
    volScalarFieldValue alpha.water 0
);

regions
(
    boxToCell       // liquid column 0 < z < {cfg.LIQUID_HEIGHT} m
    {{
        box (-1 -1 -1) (1 1 {fmt(cfg.LIQUID_HEIGHT)});
        fieldValues
        (
            volScalarFieldValue alpha.air   0
            volScalarFieldValue alpha.water 1
        );
    }}
);
""")


def write_fields(c, cfg, d):
    T = cfg.TEMPERATURE
    turb = cfg.TURBULENCE

    def field(name, dim, internal, bottom, wall, atm, cls="volScalarField"):
        c.write(f"0.orig/{name}", f"""
dimensions      {dim};

internalField   {internal};

boundaryField
{{
    bottom
    {{
{indent(bottom, 8)}
    }}
    wall
    {{
{indent(wall, 8)}
    }}
    atmosphere
    {{
{indent(atm, 8)}
    }}
}}
""", cls=cls)

    zg = "type            zeroGradient;"
    calc = "type            calculated;\nvalue           $internalField;"
    io = lambda ph, v="$internalField": (f"type            inletOutlet;\nphi             phi.{ph};\n"
                                          f"inletValue      {v};\nvalue           {v};")

    for ph in ("air", "water"):
        noslip = "type            noSlip;"
        field(f"U.{ph}", "[0 1 -1 0 0 0 0]", "uniform (0 0 0)", noslip, noslip,
              f"type            pressureInletOutletVelocity;\nphi             phi.{ph};\nvalue           $internalField;",
              cls="volVectorField")
        field(f"T.{ph}", "[0 0 0 1 0 0 0]", f"uniform {T}", zg, zg, io(ph))

    field("alpha.air", "[0 0 0 0 0 0 0]", "uniform 0", zg, zg, io("air", "uniform 1"))
    field("alpha.water", "[0 0 0 0 0 0 0]", "uniform 1", zg, zg, io("water", "uniform 0"))
    field("p", "[1 -1 -2 0 0 0 0]", f"uniform {P_ATM}", calc, calc, calc)
    ffp = "type            fixedFluxPressure;\nvalue           $internalField;"
    field("p_rgh", "[1 -1 -2 0 0 0 0]", f"uniform {P_ATM}", ffp, ffp,
          "type            prghPressure;\np               $internalField;\nvalue           $internalField;")

    def keps(ph):
        kw = "type            kqRWallFunction;\nvalue           $internalField;"
        ew = "type            epsilonWallFunction;\nvalue           $internalField;"
        nw = "type            nutkWallFunction;\nvalue           $internalField;"
        field(f"k.{ph}", "[0 2 -2 0 0 0 0]", "uniform 1e-5", kw, kw, io(ph))
        field(f"epsilon.{ph}", "[0 2 -3 0 0 0 0]", "uniform 1e-5", ew, ew, io(ph))
        field(f"nut.{ph}", "[0 2 -1 0 0 0 0]", "uniform 0", nw, nw, calc)

    def alphat(ph):
        aw = "type            compressible::alphatWallFunction;\nPrt             0.85;\nvalue           $internalField;"
        field(f"alphat.{ph}", "[1 -1 -1 0 0 0 0]", "uniform 0", aw, aw, calc)

    if turb in ("LaheyKEpsilon", "mixtureKEpsilon"):
        for ph in ("air", "water"):
            keps(ph)
            alphat(ph)
    if turb == "mixtureKEpsilon":
        field("km", "[0 2 -2 0 0 0 0]", "uniform 1e-5", zg, zg,
              "type            inletOutlet;\nphi             phim;\ninletValue      $internalField;\nvalue           $internalField;")
        field("epsilonm", "[0 2 -3 0 0 0 0]", "uniform 1e-5", zg, zg,
              "type            inletOutlet;\nphi             phim;\ninletValue      $internalField;\nvalue           $internalField;")
    if turb == "kOmegaSSTSato":
        kw = "type            kqRWallFunction;\nvalue           $internalField;"
        ow = "type            omegaWallFunction;\nvalue           $internalField;"
        nw = "type            nutkWallFunction;\nvalue           $internalField;"
        field("k.water", "[0 2 -2 0 0 0 0]", "uniform 1e-5", kw, kw, io("water"))
        field("omega.water", "[0 0 -1 0 0 0 0]", "uniform 1", ow, ow, io("water"))
        field("nut.water", "[0 2 -1 0 0 0 0]", "uniform 0", nw, nw, calc)
        alphat("water")


def write_constant(c, cfg, d):
    liq = d["liq"]
    T = cfg.TEMPERATURE
    c.write("constant/g", "dimensions      [0 1 -2 0 0 0 0];\nvalue           (0 0 -9.81);",
            cls="uniformDimensionedVectorField")

    c.write("constant/thermophysicalProperties.air", f"""
thermoType
{{
    type            heRhoThermo;
    mixture         pureMixture;
    transport       const;
    thermo          hConst;
    equationOfState perfectGas;
    specie          specie;
    energy          sensibleInternalEnergy;
}}

mixture             // [dW] Table 3.2
{{
    specie          {{ molWeight {AIR['W']}; }}
    thermodynamics  {{ Cp {AIR['Cp']}; Hf 0; }}
    transport       {{ mu {AIR['mu']}; Pr {AIR['Pr']}; }}
}}
""")
    Rl = 3000.0
    rho0 = liq["rho"] - P_ATM / (Rl * T)
    c.write("constant/thermophysicalProperties.water", f"""
// Liquid phase ("water" is the phase name): {cfg.LIQUID}, T = {T} K
// perfectFluid: rho = rho0 + p/(R T) -> {liq['rho']} kg/m3 at 1 atm.
// ([dW] used eConst + rPolynomial; v2606 has both, but no rPolynomial coefficients
//  for AG40 are given in [dW], so a weakly compressible constant density is used.)
thermoType
{{
    type            heRhoThermo;
    mixture         pureMixture;
    transport       const;
    thermo          hConst;
    equationOfState perfectFluid;
    specie          specie;
    energy          sensibleInternalEnergy;
}}

mixture
{{
    specie          {{ molWeight {liq['W']}; }}
    equationOfState {{ R {Rl}; rho0 {fmt(rho0)}; }}
    thermodynamics  {{ Cp {liq['Cp']}; Hf 0; }}
    transport       {{ mu {liq['mu']}; Pr {liq['Pr']}; }}
}}
""")

    turb = cfg.TURBULENCE
    if turb == "laminar":
        tw, ta = "simulationType  laminar;", "simulationType  laminar;"
    else:
        ras = lambda mdl: f"simulationType  RAS;\nRAS\n{{\n    RASModel        {mdl};\n    turbulence      on;\n    printCoeffs     on;\n}}"
        if turb == "LaheyKEpsilon":
            tw, ta = ras("LaheyKEpsilon"), ras("continuousGasKEpsilon")
        elif turb == "mixtureKEpsilon":
            tw, ta = ras("mixtureKEpsilon"), ras("mixtureKEpsilon")
        elif turb == "kOmegaSSTSato":
            tw, ta = ras("kOmegaSSTSato"), "simulationType  laminar;"
        else:
            raise SystemExit(f"Unknown TURBULENCE '{turb}'")
    c.write("constant/turbulenceProperties.water", tw)
    c.write("constant/turbulenceProperties.air", ta)

    # ---- phaseProperties
    db = d["db"]
    if cfg.DIAMETER_MODEL == "isothermal":
        dm = f"diameterModel   isothermal;\n    isothermalCoeffs\n    {{\n        d0              {fmt(db)};\n        p0              {fmt(d['p_inj'])};  // at the injector\n    }}"
    else:
        dm = f"diameterModel   constant;\n    constantCoeffs\n    {{\n        d               {fmt(db)};\n    }}"

    ar = cfg.ASPECT_RATIO
    ar_air = "type            constant;\n        E0              1.0;" if ar == "constant" else f"type            {ar};"

    lift = ""
    if cfg.LIFT:
        inner = "type        Tomiyama;" if cfg.LIFT == "Tomiyama" else f"type        constantCoefficient;\n            Cl          {cfg.LIFT_CL};"
        if cfg.LIFT_WALL_DAMPING_CD:
            lift = f"""
    (air in water)
    {{
        type            wallDamped;
        lift
        {{
            {inner}
        }}
        wallDamping
        {{
            type        cosine;     // 0.5 - 0.5 cos(pi min(y/(Cd d_b), 1))  = [dW] Eq. 8.13
            Cd          {cfg.LIFT_WALL_DAMPING_CD};
        }}
    }}"""
        else:
            lift = f"\n    (air in water)\n    {{\n        {inner.replace(chr(10) + '            ', chr(10) + '        ')}\n    }}"

    wl = ""
    if cfg.WALL_LUBRICATION == "Antal":
        wl = "\n    (air in water)\n    {\n        type            Antal;\n        Cw1             -0.01;\n        Cw2             0.05;\n    }"
    elif cfg.WALL_LUBRICATION == "Frank":
        wl = "\n    (air in water)\n    {\n        type            Frank;\n        Cwd             6.8;\n        Cwc             10.0;\n        p               1.7;\n    }"
    elif cfg.WALL_LUBRICATION == "Tomiyama":
        wl = f"\n    (air in water)\n    {{\n        type            Tomiyama;\n        Cwd             {fmt(cfg.TUBE_DIAMETER)};   // pipe diameter\n    }}"

    td = ""
    if cfg.TURB_DISPERSION:
        # Burns is switched on later by Allrun; start with LopezDeBertodano
        td = f"\n    (air in water)\n    {{\n        type            LopezDeBertodano;\n        Ctd             {cfg.TD_CTD};\n    }}"

    c.write("constant/phaseProperties", f"""
type            basicTwoPhaseSystem;

phases          (air water);

air
{{
    type            purePhaseModel;
    {dm}
    residualAlpha   1e-6;
}}

water
{{
    type            purePhaseModel;
    diameterModel   constant;
    constantCoeffs
    {{
        d               1e-4;      // droplets, only relevant above the free surface
    }}
    residualAlpha   1e-6;
}}

blending
{{
    default
    {{
        type            linear;
        minFullyContinuousAlpha.air   0.7;
        minPartlyContinuousAlpha.air  0.3;
        minFullyContinuousAlpha.water 0.7;
        minPartlyContinuousAlpha.water 0.3;
    }}
    drag
    {{
        type            linear;
        minFullyContinuousAlpha.air   0.7;
        minPartlyContinuousAlpha.air  0.5;
        minFullyContinuousAlpha.water 0.7;
        minPartlyContinuousAlpha.water 0.5;
    }}
}}

surfaceTension
(
    (air and water)
    {{
        type            constant;
        sigma           {liq['sigma']};
    }}
);

aspectRatio
(
    (air in water)
    {{
        {ar_air}
    }}
    (water in air)
    {{
        type            constant;
        E0              1.0;
    }}
);

drag
(
    (air in water)
    {{
        type            {cfg.DRAG};{chr(10) + '        A               24;' if cfg.DRAG == 'TomiyamaCorrelated' else ''}
        residualRe      1e-3;
        swarmCorrection {{ type none; }}
    }}
    (water in air)
    {{
        type            SchillerNaumann;
        residualRe      1e-3;
        swarmCorrection {{ type none; }}
    }}
    (air and water)
    {{
        type            segregated;
        m               0.5;
        n               8;
        swarmCorrection {{ type none; }}
    }}
);

virtualMass
(
    (air in water)
    {{
        type            constantCoefficient;
        Cvm             {cfg.VIRTUAL_MASS_CVM};
    }}
    (water in air)
    {{
        type            constantCoefficient;
        Cvm             {cfg.VIRTUAL_MASS_CVM};
    }}
);

heatTransfer
(
    (air in water)
    {{
        type            RanzMarshall;
        residualAlpha   1e-4;
    }}
    (water in air)
    {{
        type            RanzMarshall;
        residualAlpha   1e-4;
    }}
);

phaseTransfer
(
);

lift
({lift}
);

wallLubrication
({wl}
);

turbulentDispersion
({td}
);

pMin            10000;
""")

    # ---- gas injection
    c.write("constant/fvOptions", f"""
// {d['Q_lpm']} L/min ({cfg.FLOW_REFERENCE} conditions) = {d['mdot']:.4e} kg/s of air
// = {d['Q_actual_inj']*6e4:.4f} L/min actual at the injector (p = {d['p_inj']:.0f} Pa)
options
{{
    airMassSource
    {{
        type            scalarSemiImplicitSource;
        timeStart       {cfg.INJECTION_START};
        duration        {cfg.INJECTION_DURATION};
        selectionMode   cellZone;
        cellZone        injector;
        volumeMode      absolute;
        sources
        {{
            thermo:rho.air  ({d['mdot']:.6e} 0);      // kg/s
        }}
    }}

    airEnergySource     // injected gas enters at T = {cfg.TEMPERATURE} K
    {{
        type            scalarSemiImplicitSource;
        timeStart       {cfg.INJECTION_START};
        duration        {cfg.INJECTION_DURATION};
        selectionMode   cellZone;
        cellZone        injector;
        volumeMode      absolute;
        sources
        {{
            e.air           ({d['mdot']*d['e_in']:.6e} 0);   // W = mdot * e(T)
        }}
    }}
}}
""")


def write_system(c, cfg, d):
    fixed = cfg.FIXED_TIME_STEP
    dt_block = (f"deltaT          {fixed};\nadjustTimeStep  no;" if fixed else
                f"deltaT          1e-4;\nadjustTimeStep  yes;\nmaxCo           {cfg.MAX_CO};\nmaxDeltaT       {cfg.MAX_DELTA_T};")
    c.write("system/controlDict", f"""
application     reactingTwoPhaseEulerFoam;
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         {cfg.END_TIME};
{dt_block}
writeControl    adjustable;
writeInterval   {cfg.WRITE_INTERVAL};
purgeWrite      0;
writeFormat     binary;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable yes;

tAvg            {cfg.AVERAGE_START};     // start of time averaging

functions
{{
    #include "functions"
}}
""")
    c.write("system/functions", functions_dict(cfg, d))

    c.write("system/fvSchemes", r"""
ddtSchemes      { default Euler; }
gradSchemes     { default Gauss linear; }
divSchemes
{
    default                         none;
    div(phi,alpha.air)              Gauss vanLeer;
    div(phir,alpha.air)             Gauss vanLeer;
    "div\(alphaRhoPhi.*,U.*\)"      Gauss limitedLinearV 1;
    "div\(phi.*,U.*\)"              Gauss limitedLinearV 1;
    "div\(alphaRhoPhi.*,(h|e).*\)"  Gauss limitedLinear 1;
    "div\(alphaRhoPhi.*,K.*\)"      Gauss limitedLinear 1;
    "div\(alphaPhi.*,p\)"           Gauss limitedLinear 1;
    "div\(alphaRhoPhi.*,(k|epsilon|omega).*\)"  Gauss limitedLinear 1;
    "div\(phim,(k|epsilon)m\)"      Gauss limitedLinear 1;
    "div\(\(\(\(alpha.*\*thermo:rho.*\)\*nuEff.*\)\*dev2\(T\(grad\(U.*\)\)\)\)\)" Gauss linear;
}
laplacianSchemes     { default Gauss linear corrected; }
interpolationSchemes { default linear; }
snGradSchemes        { default corrected; }
wallDist             { method meshWave; nRequired true; }
""")
    relax = "" if cfg.RELAXATION == 1.0 else f'\n    fields    {{ ".*" {cfg.RELAXATION}; }}'
    c.write("system/fvSolution", f"""
solvers
{{
    "alpha.*"
    {{
        nAlphaCorr      1;
        nAlphaSubCycles 3;
    }}
    p_rgh
    {{
        solver          GAMG;
        smoother        DIC;
        tolerance       1e-8;
        relTol          0.01;
    }}
    p_rghFinal
    {{
        $p_rgh;
        relTol          0;
    }}
    "(U|e|k|epsilon|omega).*"
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-7;
        relTol          0;
        minIter         1;
    }}
}}

PIMPLE
{{
    nOuterCorrectors {cfg.N_OUTER_CORRECTORS};
    nCorrectors      {cfg.N_CORRECTORS};
    nNonOrthogonalCorrectors 0;
    faceMomentum     {'yes' if cfg.FACE_MOMENTUM else 'no'};
}}

relaxationFactors
{{
    equations {{ ".*" {cfg.RELAXATION}; }}{relax}
}}
""")
    c.write("system/decomposeParDict", f"numberOfSubdomains {cfg.N_PROCS};\nmethod          scotch;")


def functions_dict(cfg, d):
    R = d["R"]
    rmax = R * 0.995
    turb = cfg.TURBULENCE != "laminar"
    kfield = "k.water" if turb else ""
    out = []

    out.append(f"""
// ---------------------------------------------------------------- run monitors
holdup      // volume-averaged gas fraction in the liquid region
{{
    type            volFieldValue;
    libs            (fieldFunctionObjects);
    fields          (alpha.air);
    operation       volAverage;
    regionType      cellZone;
    name            liquidRegion;
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}}

gasOut      // gas mass flow leaving through the top [kg/s]
{{
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);
    regionType      patch;
    name            atmosphere;
    operation       sum;
    fields          (alphaRhoPhi.air);
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}}

freeSurfaceLines    // alpha.water along vertical lines: level = alpha.water 0.5 crossing
{{
    type            sets;
    libs            (sampling);
    writeControl    writeTime;
    interpolationScheme cell;
    setFormat       raw;
    fields          (alpha.water);
    sets
    {{
        axis   {{ type uniform; axis z; start (0 0 {fmt(cfg.LIQUID_HEIGHT - 0.05)}); end (0 0 {fmt(cfg.TUBE_HEIGHT - 1e-4)}); nPoints 400; }}
        rHalf  {{ type uniform; axis z; start ({fmt(R/2)} 0 {fmt(cfg.LIQUID_HEIGHT - 0.05)}); end ({fmt(R/2)} 0 {fmt(cfg.TUBE_HEIGHT - 1e-4)}); nPoints 400; }}
    }}
}}

// ---------------------------------------------------------------- averaging
alphaUair   // alpha-weighted gas velocity = mean(alpha U)/mean(alpha)
{{
    type            multiply;
    libs            (fieldFunctionObjects);
    fields          (alpha.air U.air);
    result          alphaU.air;
    executeControl  timeStep;
    writeControl    none;
}}

average
{{
    type            fieldAverage;
    libs            (fieldFunctionObjects);
    timeStart       $tAvg;
    restartOnRestart false;
    writeControl    writeTime;
    fields
    (
        U.water     {{ mean on; prime2Mean on;  base time; }}
        U.air       {{ mean on; prime2Mean on;  base time; }}
        alphaU.air  {{ mean on; prime2Mean off; base time; }}
        alpha.air   {{ mean on; prime2Mean on;  base time; }}{chr(10) + '        k.water     { mean on; prime2Mean off; base time; }' if turb else ''}
        p           {{ mean on; prime2Mean off; base time; }}
    );
}}

// up/down split of the MEAN liquid axial velocity ([dW] downcomer flow-rate analogue)
UzDown  {{ type exprField; libs (fieldFunctionObjects); field UzDown; timeStart $tAvg;
          expression "(U.waterMean.z() < 0) ? U.waterMean.z() : 0"; dimensions [0 1 -1 0 0 0 0]; }}
UzUp    {{ type exprField; libs (fieldFunctionObjects); field UzUp; timeStart $tAvg;
          expression "(U.waterMean.z() > 0) ? U.waterMean.z() : 0"; dimensions [0 1 -1 0 0 0 0]; }}
downMask {{ type exprField; libs (fieldFunctionObjects); field downMask; timeStart $tAvg;
          expression "(U.waterMean.z() < 0) ? 1 : 0"; dimensions [0 0 0 0 0 0 0]; }}
""")

    for i, z in enumerate(cfg.LDA_HEIGHTS, 1):
        plane = (f"sampledSurfaceDict {{ type cuttingPlane; planeType pointAndNormal; "
                 f"pointAndNormalDict {{ point (0 0 {fmt(z)}); normal (0 0 1); }} interpolate false; }}")
        out.append(f"""
// ---------------------------------------------------------------- plane {i}: z = {z} m
voidZ{i}        // instantaneous area-averaged void fraction
{{
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);
    regionType      sampledSurface;
    name            planeZ{i};
    {plane}
    operation       areaAverage;
    fields          (alpha.air);
    writeFields     false;
    writeControl    timeStep;
    writeInterval   10;
}}

meanVoidZ{i}    // area average of the time-averaged fields
{{
    $voidZ{i};
    timeStart       $tAvg;
    fields          (alpha.airMean);
    writeControl    writeTime;
    writeInterval   1;
}}

flowZ{i}        // area integrals: Q_down = int(UzDown), Q_up = int(UzUp), A_down = int(downMask)
{{
    $voidZ{i};
    timeStart       $tAvg;
    operation       areaIntegrate;
    fields          (UzDown UzUp downMask);
    writeControl    writeTime;
    writeInterval   1;
}}
""")

    # probes at LDA points
    pts = []
    for z in cfg.LDA_HEIGHTS:
        for a in cfg.LDA_ANGLES:
            th = math.radians(a)
            for r in cfg.LDA_RADII:
                pts.append(f"({fmt(r*math.cos(th))} {fmt(r*math.sin(th))} {fmt(z)})")
    pfields = "U.water alpha.air" + (" k.water" if turb else "")
    if pts:
        out.append(f"""
// ---------------------------------------------------------------- LDA points
// order: for each height, for each angle, for each radius (see caseSummary.txt)
ldaProbes
{{
    type            probes;
    libs            (sampling);
    timeStart       $tAvg;
    fields          ({pfields});
    writeControl    timeStep;
    writeInterval   {cfg.PROBE_WRITE_EVERY};
    probeLocations
    (
{indent(chr(10).join(pts), 8)}
    );
}}
""")

    sets = []
    for i, z in enumerate(cfg.LDA_HEIGHTS, 1):
        sets.append(f"z{i}x {{ $_line; start ({fmt(-rmax)} 0 {fmt(z)}); end ({fmt(rmax)} 0 {fmt(z)}); }}")
        sets.append(f"z{i}y {{ $_line; start (0 {fmt(-rmax)} {fmt(z)}); end (0 {fmt(rmax)} {fmt(z)}); }}")
    surfs = [f"z{i} {{ $_plane; pointAndNormalDict {{ point (0 0 {fmt(z)}); normal (0 0 1); }} }}"
             for i, z in enumerate(cfg.LDA_HEIGHTS, 1)]
    mean_fields = "U.waterMean U.airMean alphaU.airMean alpha.airMean U.waterPrime2Mean" + (" k.waterMean" if turb else "")
    out.append(f"""
// ---------------------------------------------------------------- mean profiles
ldaLines
{{
    type            sets;
    libs            (sampling);
    writeControl    writeTime;
    timeStart       $tAvg;
    interpolationScheme cellPoint;
    setFormat       csv;
    fields          ({mean_fields});
    _line           {{ type uniform; axis xyz; nPoints 101; }}
    sets
    {{
{indent(chr(10).join(sets), 8)}
    }}
}}

ldaPlanes
{{
    type            surfaces;
    libs            (sampling);
    writeControl    writeTime;
    timeStart       $tAvg;
    surfaceFormat   raw;
    interpolate     false;
    fields          ({mean_fields});
    _plane          {{ type cuttingPlane; planeType pointAndNormal; }}
    surfaces
    {{
{indent(chr(10).join(surfs), 8)}
    }}
}}
""")
    if cfg.WRITE_PHASE_FORCES:
        out.append("""
phaseForces
{
    type            phaseForces;
    libs            (phaseFunctionObjects);
    phase           air;
    writeControl    writeTime;
}
""")
    return "\n".join(o.strip("\n") + "\n" for o in out)


def write_scripts(c, cfg, d):
    par = cfg.N_PROCS > 1
    run = ("runApplication decomposePar\n" if par else "")
    solver = ('runParallel -s {s} $(getApplication)' if par else 'runApplication -s {s} $(getApplication)')
    burns = cfg.TURB_DISPERSION == "Burns"
    body = f"""#!/bin/sh
cd "${{0%/*}}" || exit
. ${{WM_PROJECT_DIR:?}}/bin/tools/RunFunctions
#------------------------------------------------------------------------------
# generated by setupCase.py

restore0Dir
runApplication blockMesh
runApplication checkMesh
runApplication topoSet
runApplication setFields
{run}"""
    if burns:
        td_burns = (f"((air in water) {{ type Burns; sigma {cfg.TD_SIGMA}; Ctd {cfg.TD_CTD}; residualAlpha 1e-4; }})")
        body += f"""
# Stage 1: LopezDeBertodano turbulent dispersion from the still column
# (v2606 Burns diverges at t ~ 0.03 s when started from rest)
foamDictionary -entry endTime -set {cfg.BURNS_START_TIME} system/controlDict
foamDictionary -entry writeInterval -set {cfg.BURNS_START_TIME} system/controlDict
{solver.format(s='stage1')}

# Stage 2: switch to Burns and continue
foamDictionary -entry turbulentDispersion -set '{td_burns}' constant/phaseProperties
foamDictionary -entry endTime -set {cfg.END_TIME} system/controlDict
foamDictionary -entry writeInterval -set {cfg.WRITE_INTERVAL} system/controlDict
{solver.format(s='stage2')}
"""
    else:
        body += f"\n{solver.format(s='run')}\n"
    if par:
        body += "\nrunApplication reconstructPar -latestTime\n"
    body += "\n#------------------------------------------------------------------------------\n"
    c.write_raw("Allrun", body, executable=True)
    c.write_raw("Allclean", """#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions
cleanCase0
""", executable=True)


def write_summary(c, cfg, d, warnings, cfg_path):
    m = d["mesh"]
    lines = [
        f"Case generated by setupCase.py from {cfg_path}",
        "",
        f"Liquid                 : {cfg.LIQUID}  rho={d['liq']['rho']}  mu={d['liq']['mu']}  sigma={d['liq']['sigma']}",
        f"Gas flowrate           : {d['Q_lpm']} L/min ({cfg.FLOW_REFERENCE}) -> mdot = {d['mdot']:.4e} kg/s",
        f"                         superficial j_g = {1e3*d['jg']:.2f} mm/s",
        f"Bubble diameter        : {1e3*d['db']:.3f} mm  [{d['db_src']}]  model {cfg.DIAMETER_MODEL}",
        f"Eo / Mo / Re_b(U=0.4)  : {d['Eo']:.2f} / {d['Mo']:.2e} / {d['Re_b']:.0f}",
        f"Tomiyama C_L           : {d['CL']:+.3f}   (sign change at d_b = {1e3*d['d_CL0']:.2f} mm for this liquid)",
        f"Turbulence             : {cfg.TURBULENCE}",
        f"Interfacial            : drag {cfg.DRAG}, lift {cfg.LIFT} (damping Cd={cfg.LIFT_WALL_DAMPING_CD}), "
        f"WL {cfg.WALL_LUBRICATION}, TD {cfg.TURB_DISPERSION} (Ctd {cfg.TD_CTD}), Cvm {cfg.VIRTUAL_MASS_CVM}",
        "",
        f"Mesh                   : {cfg.MESH_LEVEL if not cfg.MESH_CUSTOM else 'custom'}  Nc={m['Nc']} Nr={m['Nr']} Nz={m['Nz']}  -> {m['cells']} cells",
        f"Cell sizes [mm]        : core {1e3*m['d_core']:.2f}, arc {1e3*m['d_arc']:.2f}, radial (mean) {1e3*m['d_rad_mean']:.2f}, "
        f"radial (wall) {1e3*m['d_rad_wall']:.2f}, dz {1e3*m['dz']:.2f}, h=(V/N)^1/3 {1e3*m['h']:.2f}",
        f"Cell / d_b             : core {m['d_core']/d['db']:.2f}, arc {m['d_arc']/d['db']:.2f}, dz {m['dz']/d['db']:.2f}, h {m['h']/d['db']:.2f}",
        f"Injector zone          : r = {1e3*d['inj_r']:.2f} mm, h = {1e3*d['inj_h']:.2f} mm (~{d['inj_cells_est']:.0f} cells)",
        "",
        f"LDA heights [m]        : {cfg.LDA_HEIGHTS}",
        f"LDA radii [m]          : {cfg.LDA_RADII}",
        f"LDA angles [deg]       : {cfg.LDA_ANGLES}",
        (f"Probe index            : i = (iz*{len(cfg.LDA_ANGLES)} + ia)*{len(cfg.LDA_RADII)} + ir" if cfg.LDA_ANGLES else "Probes                 : none"),
        "",
        "Warnings:" if warnings else "Warnings: none",
    ] + [f"  - {w}" for w in warnings]
    c.write_raw("caseSummary.txt", "\n".join(lines) + "\n")
    return lines


# ============================================================================= questionnaire
class Ask:
    """Small input helpers: every question shows its suggested answer, Enter accepts it."""

    @staticmethod
    def _read(prompt):
        try:
            return input(prompt).strip()
        except EOFError:
            print()
            return ""

    @staticmethod
    def choice(question, options, default, notes=None):
        """options: list of (value, description). Returns the chosen value."""
        print(f"\n{question}")
        keys = [o[0] for o in options]
        for i, (val, desc) in enumerate(options, 1):
            mark = "  <- suggested" if val == default else ""
            print(f"   {i}) {desc}{mark}")
        if notes:
            print(f"   ({notes})")
        dflt = keys.index(default) + 1
        while True:
            a = Ask._read(f"   choose 1-{len(options)} [{dflt}]: ")
            if not a:
                return default
            if a.isdigit() and 1 <= int(a) <= len(options):
                return keys[int(a) - 1]
            print(f"   ! please type a number between 1 and {len(options)}")

    @staticmethod
    def number(question, default, lo, hi, unit="", pattern=None, pattern_hint=None, soft=None):
        """Float in [lo, hi]. pattern: regex the text must match. soft=(a, b): outside -> confirm."""
        print(f"\n{question}")
        while True:
            a = Ask._read(f"   value{(' [' + unit + ']') if unit else ''} [{default}]: ") or str(default)
            if pattern and not re.fullmatch(pattern, a):
                print(f"   ! format must be {pattern_hint}")
                continue
            try:
                v = float(a)
            except ValueError:
                print("   ! not a number")
                continue
            if not lo <= v <= hi:
                print(f"   ! must be between {lo:g} and {hi:g} {unit}")
                continue
            if soft and not soft[0] <= v <= soft[1]:
                if not Ask.yes(f"   {v} {unit} is outside the suggested range {soft[0]}-{soft[1]} {unit}. Use it anyway?", False):
                    continue
            return v

    @staticmethod
    def numbers(question, default, lo, hi, unit="", pattern=None, pattern_hint=None, soft=None):
        """Comma-separated list of floats."""
        print(f"\n{question}")
        dtxt = ", ".join(f"{x:g}" for x in default)
        while True:
            a = Ask._read(f"   values{(' [' + unit + ']') if unit else ''} [{dtxt}]: ") or dtxt
            items = [x.strip() for x in a.replace(";", ",").split(",") if x.strip()]
            bad = [x for x in items if pattern and not re.fullmatch(pattern, x)]
            if bad:
                print(f"   ! {', '.join(bad)}: format must be {pattern_hint}")
                continue
            try:
                vals = [float(x) for x in items]
            except ValueError:
                print("   ! not a list of numbers")
                continue
            out = [v for v in vals if not lo <= v <= hi]
            if out or not vals:
                print(f"   ! every value must be between {lo:g} and {hi:g} {unit}")
                continue
            if soft and any(not soft[0] <= v <= soft[1] for v in vals):
                if not Ask.yes(f"   some values are outside the suggested range {soft[0]}-{soft[1]} {unit}. Use them anyway?", False):
                    continue
            return sorted(set(vals))

    @staticmethod
    def yes(question, default):
        while True:
            a = Ask._read(f"{question} [{'Y/n' if default else 'y/N'}]: ").lower()
            if not a:
                return default
            if a in ("y", "yes"):
                return True
            if a in ("n", "no"):
                return False


def section(i, n, title):
    print(f"\n{'=' * 78}\n [{i}/{n}] {title}\n{'=' * 78}")


def mesh_table(cfg, db):
    rows = []
    for lvl, m in MESH_LEVELS.items():
        Nz = max(1, round(cfg.TUBE_HEIGHT / m["dz"]))
        cells = (m["Nc"] ** 2 + 4 * m["Nc"] * m["Nr"]) * Nz
        h = (math.pi * (cfg.TUBE_DIAMETER / 2) ** 2 * cfg.TUBE_HEIGHT / cells) ** (1 / 3)
        core = 2 * cfg.CORE_HALF_SIDE / m["Nc"]
        desc = (f"{lvl:<9}  {cells/1000:6.1f} k cells   mean cell {1e3*h:.1f} mm   "
                f"cell/d_b {min(core, m['dz'])/db:.2f}-{max(h, m['dz'])/db:.2f}")
        rows.append((lvl, desc))
    return rows


def questionnaire(cfg):
    N = 6
    print("\nBubbly-tube case set-up (OpenFOAM v2606, reactingTwoPhaseEulerFoam)")
    print("Press Enter to accept the suggested answer shown in [brackets].")
    print(f"Fixed: tube diameter {1e3*cfg.TUBE_DIAMETER:.0f} mm, liquid level {1e3*cfg.LIQUID_HEIGHT:.0f} mm, "
          f"injector centred, T = {cfg.TEMPERATURE} K.")

    # ------------------------------------------------------------------ 1
    section(1, N, "Operating conditions")
    cfg.LIQUID = Ask.choice("Liquid?", [
        ("AG40", "40 wt% aqueous glycerol  (rho 1100, mu 3.63 mPa s, sigma 0.070) - thesis fluid"),
        ("water", "water                    (rho 998,  mu 1.00 mPa s, sigma 0.073)"),
    ], cfg.LIQUID)
    qd = cfg.Q_LPM if isinstance(cfg.Q_LPM, (list, tuple)) else [cfg.Q_LPM]
    cfg.Q_LPM = Ask.numbers(
        "Gas flowrate(s) in L/min. Suggested range 0.1-0.5, format *.* (e.g. 0.3).\n"
        "   Several values separated by commas give one case each (e.g. 0.1, 0.3, 0.5).",
        qd, 0.0, 9.9, "L/min", pattern=r"\d\.\d", pattern_hint="*.* (one digit, point, one digit, e.g. 0.3)",
        soft=(0.1, 0.5))
    cfg.FLOW_REFERENCE = Ask.choice("In which conditions is the flowrate given?", [
        ("actual", "actual litres at 20 C, 1 atm (as used in the thesis)"),
        ("normal", "normal litres, 0 C, 1 atm (Bronkhorst 'ln/min'; ~7 % more gas mass)"),
        ("standard", "standard litres, 20 C, 1 atm"),
    ], cfg.FLOW_REFERENCE)

    # ------------------------------------------------------------------ 2
    section(2, N, "Geometry and mesh")
    cfg.TUBE_HEIGHT = Ask.number(
        f"Tube height in m (the liquid level stays at {cfg.LIQUID_HEIGHT:.2f} m; the rest is air head space).\n"
        "   Format *.** (e.g. 0.35). Thesis rig: 0.45 m; thesis free-surface CFD: 0.50 m.",
        cfg.TUBE_HEIGHT, cfg.LIQUID_HEIGHT + 0.02, 1.5, "m", pattern=r"\d\.\d\d",
        pattern_hint="*.** (e.g. 0.35)", soft=(0.35, 0.60))
    db0 = bubble_diameter(cfg, cfg.Q_LPM[0])[0]
    cfg.MESH_CUSTOM = None
    cfg.MESH_LEVEL = Ask.choice(
        f"Mesh (curved O-grid; cell/d_b evaluated for d_b = {1e3*db0:.2f} mm at {cfg.Q_LPM[0]} L/min)?",
        mesh_table(cfg, db0), cfg.MESH_LEVEL,
        notes="thesis mesh study: coarse 19k / medium 50k / fine 128k / extrafine 309k cells for 0.30 m")

    # ------------------------------------------------------------------ 3
    section(3, N, "Bubbles")
    tab = ", ".join(f"{q:g} L/min -> {1e3*bubble_diameter(cfg, q)[0]:.2f} mm" for q in cfg.Q_LPM)
    src = Ask.choice("Bubble diameter?", [
        ("auto", f"from the thesis riser measurements (5 -> 8.5 mm for 0.1 -> 0.5 L/min): {tab}"),
        ("fixed", "one value for all flowrates (you type it)"),
    ], "auto" if cfg.BUBBLE_DIAMETER == "auto" else "fixed")
    if src == "fixed":
        dflt = 6.0 if cfg.BUBBLE_DIAMETER == "auto" else round(1e3 * cfg.BUBBLE_DIAMETER, 1)
        cfg.BUBBLE_DIAMETER = 1e-6 * round(1e3 * Ask.number(
            "Bubble diameter in mm, format *.* (e.g. 6.5). Tomiyama lift changes sign at ~6.3 mm (AG40) / ~5.8 mm (water).",
            dflt, 0.5, 20.0, "mm", pattern=r"\d{1,2}\.\d", pattern_hint="*.* (e.g. 6.5)", soft=(1.0, 10.0)))
    else:
        cfg.BUBBLE_DIAMETER = "auto"
    cfg.DIAMETER_MODEL = Ask.choice("Bubble size model?", [
        ("isothermal", "isothermal: grows with the hydrostatic pressure drop (~3 %) - thesis"),
        ("constant", "constant"),
    ], cfg.DIAMETER_MODEL)

    # ------------------------------------------------------------------ 4
    section(4, N, "Physics")
    cfg.TURBULENCE = Ask.choice("Turbulence model?", [
        ("laminar", "laminar (no turbulent dispersion possible, see note)"),
        ("LaheyKEpsilon", "RAS k-epsilon with bubble-induced turbulence: LaheyKEpsilon + continuousGasKEpsilon (thesis setup B)"),
        ("kOmegaSSTSato", "RAS k-omega SST with Sato BIT viscosity + laminar gas (thesis setup C; mesh-converged in the thesis)"),
        ("mixtureKEpsilon", "RAS mixture k-epsilon (v2606 bubbleColumn tutorial)"),
    ], cfg.TURBULENCE,
        notes="thesis downcomer Re = 225-550: laminar bulk with bubble-induced pseudo-turbulence")
    cfg.DRAG = Ask.choice("Drag model?", [
        ("IshiiZuber", "Ishii-Zuber (thesis)"),
        ("TomiyamaCorrelated", "Tomiyama correlated, slightly contaminated (A = 24)"),
        ("TomiyamaAnalytic", "Tomiyama analytic (uses the aspect ratio)"),
        ("SchillerNaumann", "Schiller-Naumann (spheres)"),
    ], cfg.DRAG)
    cfg.LIFT = Ask.choice("Lift force?", [
        ("Tomiyama", "Tomiyama correlation (thesis)"),
        ("constant", f"constant coefficient C_L = {cfg.LIFT_CL}"),
        (None, "no lift"),
    ], cfg.LIFT)
    if cfg.LIFT:
        cd = Ask.number("Lift wall damping: cosine damping over Cd x d_b from the wall (thesis Eq. 8.13 = 1.0; 0 = no damping).",
                        cfg.LIFT_WALL_DAMPING_CD or 0.0, 0.0, 5.0)
        cfg.LIFT_WALL_DAMPING_CD = cd if cd > 0 else None
    cfg.WALL_LUBRICATION = Ask.choice("Wall lubrication?", [
        (None, "none (thesis: lift wall damping instead)"),
        ("Antal", "Antal"), ("Frank", "Frank"), ("Tomiyama", "Tomiyama (pipe diameter)"),
    ], cfg.WALL_LUBRICATION)
    if cfg.TURBULENCE == "laminar":
        print("\n   Turbulent dispersion: skipped - all v2606 models scale with the liquid k or nut, which are 0 when laminar.")
        cfg.TURB_DISPERSION = None
    else:
        cfg.TURB_DISPERSION = Ask.choice("Turbulent dispersion?", [
            ("LopezDeBertodano", "Lopez de Bertodano, F = -Ctd rho k grad(alpha) (thesis setup B)"),
            ("Burns", "Burns (thesis setup C) - WARNING: diverged in v2606 tests with AG40"),
            (None, "none"),
        ], cfg.TURB_DISPERSION or "LopezDeBertodano")
        if cfg.TURB_DISPERSION:
            dflt = cfg.TD_CTD if cfg.TURB_DISPERSION == "LopezDeBertodano" else 1.0
            cfg.TD_CTD = Ask.number("Turbulent dispersion coefficient Ctd (thesis: 2.0 Lopez, 1.0 Burns; literature 0.1-1.0).",
                                    dflt, 0.0, 5.0, soft=(0.1, 3.0))

    # ------------------------------------------------------------------ 5
    section(5, N, "Measurements (LDA planes)")
    cfg.LDA_HEIGHTS = Ask.numbers(
        "Heights of the LDA planes in m, comma separated, format 0.** (e.g. 0.15).\n"
        "   Each plane gets LDA-point probes, mean profiles and the surface-averaged void fraction.\n"
        f"   Allowed 0.02-{cfg.LIQUID_HEIGHT - 0.02:.2f} m (above the injector, below the free surface).",
        cfg.LDA_HEIGHTS, 0.02, cfg.LIQUID_HEIGHT - 0.02, "m", pattern=r"0\.\d{1,3}", pattern_hint="0.** (e.g. 0.15)")
    layout = Ask.choice("LDA points on each plane?", [
        ("8", "thesis radii (10 per path, 0.5-14.5 mm) on 8 radial paths (every 45 deg) = 80 points/plane"),
        ("4", "thesis radii on 4 radial paths (every 90 deg) = 40 points/plane (smaller files)"),
        ("0", "no LDA-point probes (mean profiles and plane averages only)"),
    ], "8" if len(cfg.LDA_ANGLES) == 8 else ("4" if cfg.LDA_ANGLES else "0"))
    cfg.LDA_ANGLES = {"8": [0, 45, 90, 135, 180, 225, 270, 315], "4": [0, 90, 180, 270], "0": []}[layout]

    # ------------------------------------------------------------------ 6
    section(6, N, "Run control")
    cfg.END_TIME = Ask.number("Simulated time in s (thesis: 40 s).", cfg.END_TIME, 1.0, 1000.0, "s")
    cfg.AVERAGE_START = Ask.number("Start of time averaging in s (after the start-up transient).",
                                   min(cfg.AVERAGE_START, cfg.END_TIME / 2), 0.0, cfg.END_TIME - 0.5, "s")
    ncpu = os.cpu_count() or 1
    cfg.N_PROCS = int(Ask.number(f"Number of processors (this machine has {ncpu}; thesis: 16).",
                                 min(cfg.N_PROCS, ncpu), 1, 1024, pattern=r"\d+", pattern_hint="an integer"))

    if Ask.yes("\nChange advanced settings (time step, numerics, aspect ratio, output)?", False):
        advanced(cfg)
    return cfg


def advanced(cfg):
    section("A", "A", "Advanced settings")
    ts = Ask.choice("Time step?", [
        ("adaptive", f"adaptive, max Courant {cfg.MAX_CO}, max dt {cfg.MAX_DELTA_T} s"),
        ("fixed", "fixed dt = 1 ms (thesis)"),
    ], "fixed" if cfg.FIXED_TIME_STEP else "adaptive")
    cfg.FIXED_TIME_STEP = 1e-3 if ts == "fixed" else None
    if ts == "adaptive":
        cfg.MAX_CO = Ask.number("Maximum Courant number.", cfg.MAX_CO, 0.05, 2.0)
    cfg.RELAXATION = Ask.number("Relaxation factor (1 = none; thesis 0.85).", cfg.RELAXATION, 0.3, 1.0)
    cfg.N_OUTER_CORRECTORS = int(Ask.number("PIMPLE outer correctors (thesis 3).", cfg.N_OUTER_CORRECTORS, 1, 20,
                                            pattern=r"\d+", pattern_hint="an integer"))
    cfg.FACE_MOMENTUM = Ask.yes("Use faceMomentum (damps free-surface oscillations)?", cfg.FACE_MOMENTUM)
    cfg.ASPECT_RATIO = Ask.choice("Bubble aspect ratio model?", [
        ("constant", "constant E = 1 (thesis)"), ("Wellek", "Wellek"),
        ("VakhrushevEfremov", "Vakhrushev-Efremov"), ("Tomiyama", "Tomiyama"),
    ], cfg.ASPECT_RATIO)
    cfg.VIRTUAL_MASS_CVM = Ask.number("Virtual mass coefficient (thesis 0.5).", cfg.VIRTUAL_MASS_CVM, 0.0, 2.0)
    cfg.WRITE_INTERVAL = Ask.number("Write interval in s.", cfg.WRITE_INTERVAL, 0.01, cfg.END_TIME, "s")
    cfg.PROBE_WRITE_EVERY = int(Ask.number("Write LDA probes every N time steps.", cfg.PROBE_WRITE_EVERY, 1, 1000,
                                           pattern=r"\d+", pattern_hint="an integer"))
    cfg.WRITE_PHASE_FORCES = Ask.yes("Write the interfacial force fields (phaseForces)?", cfg.WRITE_PHASE_FORCES)
    cfg.INJECTOR_DIAMETER = 1e-6 * round(1e3 * Ask.number("Injector orifice diameter in mm (thesis 1.0).",
                                              1e3 * cfg.INJECTOR_DIAMETER, 0.1, 10.0, "mm"))


def print_overview(cfg):
    print(f"\n{'=' * 78}\n Summary\n{'=' * 78}")
    rows = [
        ("liquid", cfg.LIQUID), ("flowrate(s)", f"{', '.join(f'{q:g}' for q in cfg.Q_LPM)} L/min ({cfg.FLOW_REFERENCE})"),
        ("tube / liquid height", f"{cfg.TUBE_HEIGHT} m / {cfg.LIQUID_HEIGHT} m"), ("mesh", cfg.MESH_LEVEL),
        ("bubble diameter", ", ".join(f"{1e3*bubble_diameter(cfg, q)[0]:.2f} mm" for q in cfg.Q_LPM) + f" ({cfg.DIAMETER_MODEL})"),
        ("turbulence", cfg.TURBULENCE),
        ("forces", f"drag {cfg.DRAG}, lift {cfg.LIFT} (damping {cfg.LIFT_WALL_DAMPING_CD}), "
                   f"wall lub. {cfg.WALL_LUBRICATION}, TD {cfg.TURB_DISPERSION}"
                   + (f" (Ctd {cfg.TD_CTD})" if cfg.TURB_DISPERSION else "")),
        ("LDA heights", f"{cfg.LDA_HEIGHTS} m, {len(cfg.LDA_ANGLES)} radial paths"),
        ("run", f"{cfg.END_TIME} s, averaging from {cfg.AVERAGE_START} s, {cfg.N_PROCS} processors"),
    ]
    for k, v in rows:
        print(f"   {k:<22}: {v}")


# ============================================================================= main
def main():
    argv = sys.argv[1:]
    force = "--force" in argv
    if "--from" in argv:
        src = os.path.abspath(argv[argv.index("--from") + 1])
        cfg, interactive, note = load_config(src), False, f"replayed from {src}"
    else:
        cfg = load_config(os.path.join(HERE, "caseDefaults.py"))
        interactive = "--defaults" not in argv
        note = "questionnaire" if interactive else "caseDefaults.py"
    if not isinstance(cfg.Q_LPM, (list, tuple)):
        cfg.Q_LPM = [cfg.Q_LPM]

    if interactive:
        questionnaire(cfg)
        print_overview(cfg)
        if not Ask.yes("\nCreate the case(s)?", True):
            raise SystemExit("nothing written")

    if cfg.LIQUID not in FLUIDS:
        raise SystemExit(f"LIQUID must be one of {list(FLUIDS)}")
    if not cfg.MESH_CUSTOM and cfg.MESH_LEVEL not in MESH_LEVELS:
        raise SystemExit(f"MESH_LEVEL must be one of {list(MESH_LEVELS)}")
    base = cfg.OUTPUT_DIR if os.path.isabs(cfg.OUTPUT_DIR) else os.path.join(HERE, cfg.OUTPUT_DIR)

    for Q in cfg.Q_LPM:
        d = derive(cfg, Q)
        name = cfg.CASE_NAME.format(Q=f"{Q:g}", db=f"{1e3*d['db']:.3g}mm",
                                    turb=TURB_TAGS.get(cfg.TURBULENCE, cfg.TURBULENCE),
                                    mesh=cfg.MESH_LEVEL if not cfg.MESH_CUSTOM else "custom")
        root = os.path.join(base, name)
        if os.path.exists(root):
            if not (force or (interactive and Ask.yes(f"\n{root} exists. Overwrite?", False))):
                print(f"[skip] {root}")
                continue
            shutil.rmtree(root)
        os.makedirs(root)
        c = Case(root)
        warnings = checks(cfg, d)
        write_mesh(c, cfg, d)
        write_fields(c, cfg, d)
        write_constant(c, cfg, d)
        write_system(c, cfg, d)
        write_scripts(c, cfg, d)
        one = types.SimpleNamespace(**vars(cfg))
        one.Q_LPM = [Q]
        save_config(one, os.path.join(root, "caseSettings.py"), note)
        lines = write_summary(c, cfg, d, warnings, note)
        print(f"\n=== {root}")
        print("\n".join(lines))


if __name__ == "__main__":
    main()
